#!/usr/bin/env bash
# ================================================================
# bootstrap-backend.sh
#
# Run ONCE before terraform init.
# Creates the S3 bucket and DynamoDB table for remote state.
# Bucket name: ecommerce-tfstate-<YOUR_ACCOUNT_ID>  (globally unique)
# ================================================================
set -euo pipefail

REGION=$(aws configure get region 2>/dev/null || echo "us-east-1")
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
BUCKET="ecommerce-tfstate-${ACCOUNT_ID}"
TABLE="ecommerce-tfstate-lock"

echo "=================================="
echo "Account:  $ACCOUNT_ID"
echo "Region:   $REGION"
echo "Bucket:   $BUCKET"
echo "DynamoDB: $TABLE"
echo "=================================="

# Create S3 bucket
if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "✓ S3 bucket already exists"
else
  echo "Creating S3 bucket..."
  if [ "$REGION" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration LocationConstraint="$REGION"
  fi
  echo "✓ Created: $BUCKET"
fi

aws s3api put-bucket-versioning \
  --bucket "$BUCKET" --versioning-configuration Status=Enabled

aws s3api put-bucket-encryption \
  --bucket "$BUCKET" \
  --server-side-encryption-configuration \
  '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'

aws s3api put-public-access-block \
  --bucket "$BUCKET" \
  --public-access-block-configuration \
  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

echo "✓ S3 bucket configured (versioning, encryption, public block)"

# Create DynamoDB table for state locking
if aws dynamodb describe-table --table-name "$TABLE" --region "$REGION" 2>/dev/null; then
  echo "✓ DynamoDB table already exists"
else
  echo "Creating DynamoDB lock table..."
  aws dynamodb create-table \
    --table-name "$TABLE" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$REGION"
  echo "✓ Created: $TABLE"
fi

# Write backend.hcl with real values
cat > ../terraform/backend.hcl << EOF
# Generated by bootstrap-backend.sh — do not commit to git
bucket         = "${BUCKET}"
key            = "eks/terraform.tfstate"
region         = "${REGION}"
encrypt        = true
dynamodb_table = "${TABLE}"
EOF

echo ""
echo "✓ Generated: terraform/backend.hcl"
echo ""
echo "Next steps:"
echo "  cd ../terraform"
echo "  export TF_VAR_github_username=YOUR_GITHUB_USERNAME"
echo "  terraform init -backend-config=backend.hcl"
echo "  terraform plan"
echo "  terraform apply"
