# AUTO-GENERATED by terraform apply
# Source: ecommerce-infra/terraform/templates/argocd-app.yaml.tpl
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: ${environment}
spec:
  project: default
  source:
    repoURL: "https://github.com/${github_username}/ecommerce-k8s-gitops.git"
    targetRevision: main
    path: overlays/eks-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /secrets
