# AUTO-GENERATED by terraform apply
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-prod

resources:
  - namespace.yaml

helmCharts:
  - name: ecommerce
    releaseName: ecommerce-prod
    version: "1.0.0"
    includeCRDs: false
    valuesFile: values-prod.yaml
    chartHome: ../../charts

# Image tags updated by Jenkins CI after each build
images:
%{ for svc in services ~}
  - name: ${svc}
    newName: ${ecr_registry}/${svc}
    newTag: latest
%{ endfor ~}
