# AUTO-GENERATED by terraform apply
global:
  namespace: ecommerce-prod
  environment: ${environment}
  registry: "${ecr_registry}"
  imageTag: "latest"

replicas:
  frontend:     3
  admin:        2
  gateway:      4
  userAuth:     3
  catalog:      3
  shopping:     3
  inventory:    2
  orderPayment: 3
  fulfillment:  2
  platform:     2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 15
  cpuThreshold: 65
  memoryThreshold: 75

ingress:
  enabled: true
  useAlbDns: true

config:
  nodeEnv: "production"
  logLevel: "warn"

monitoring:
  serviceMonitor:
    enabled: true
    interval: "30s"
    path: "/metrics"
